readonly OMADORA_LIBEXEC_DIR="$OMADORA_ROOT/libexec"
readonly OMADORA_LIB_DIR="$OMADORA_ROOT/lib"

readonly OMADORA_THEMES_DIR="$OMADORA_ROOT/themes"
readonly OMADORA_DEFAULTS_DIR="$OMADORA_ROOT/defaults"

readonly OMADORA_MIGRATIONS_DIR="$OMADORA_ROOT/migrations"

export OMADORA_LIBEXEC_DIR
export OMADORA_LIB_DIR
export OMADORA_THEMES_DIR
export OMADORA_DEFAULTS_DIR
export OMADORA_MIGRATIONS_DIR
