# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Source the default Omadora bash config
# (don't mess with these directly, just overwrite them in ~/.bashrc.d)
. ~/.local/share/omadora/default/bash/rc

# Source user bash config
if [ -d "$HOME"/.bashrc.d ]; then
  for rc in "$HOME"/.bashrc.d/*; do
    if [ -f "$rc" ]; then
      . "$rc"
    fi
  done
fi
unset rc
