# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omadora aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omadora/default/bash/rc

# Source user config from .bashrc.d
if [ -d "$HOME"/.bashrc.d ]; then
  for rc in "$HOME"/.bashrc.d/*; do
    if [ -f "$rc" ]; then
      source "$rc"
    fi
  done
fi
unset rc
