# Wofi menu as window
windowrule = float on, match:class wofi
windowrule = stay_focused on, match:class wofi
windowrule = pin on, match:class wofi
windowrule = dim_around on, match:class wofi

# Wofi menu as layer
layerrule = dim_around on, match:namespace wofi
