# Wofi menu window
windowrule = float on, match:class wofi
windowrule = stay_focused on, match:class wofi
windowrule = pin on, match:class wofi
windowrule = dim_around on, match:class wofi
windowrule = opacity 0.95 0.9, match:class wofi
