# Float xfce-polkit authentication agent
windowrule = float on, match:class xfce-polkit
windowrule = center on, match:class xfce-polkit
windowrule = pin on, match:class xfce-polkit
windowrule = dim_around on, match:class xfce-polkit
