[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#A1A8C9"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#CBA6F7"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#87B0F9"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#87B0F9"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#87B0F9"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#43465A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#87B0F9"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#CDD6F4"

[colors.bright]
black = "#43465A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#87B0F9"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A1A8C9"

[colors.dim]
black = "#43465A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#87B0F9"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A1A8C9"

[[colors.indexed_colors]]
index = 16
color = "#CBA6F7"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"
