general {
    lock_cmd = systemctl --user start omadora-hyprlock.service
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = omadora-brightness-display on
    inhibit_sleep = 3
}

# Start screensaver after 2.5 minutes
listener {
    timeout = 150
    on-timeout = pidof hyprlock || omadora-launch-screensaver
}

# Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
listener {
    timeout = 152
    on-timeout = loginctl lock-session
}

# Screen off after 7.5 minutes
listener {
    timeout = 154
    on-timeout = omadora-brightness-display off
    on-resume = omadora-brightness-display on
}
