general {
    lock_cmd = pgrep -x hyprlock || omadora-system-lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on; brightnessctl -r
    inhibit_sleep = 3
}

listener {
    timeout = 150
    on-timeout = pgrep -x hyprlock || omadora-launch-screensaver
}

listener {
    timeout = 300
    on-timeout = playerctl pause || true; loginctl lock-session && sleep 1 && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
