#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common/init.sh"

# shellcheck source=lib/common/cli.sh
source "$OMADORA_LIB_DIR/common/cli.sh"

# -----------------------------------------------------------------------------
# CLI Definition
# -----------------------------------------------------------------------------

CLI_GROUP="cmd"
CLI_SUMMARY="Run misc Omadora commands"

CLI_NAMESPACES=()

CLI_COMMANDS=(
  "transcode||Transcode media|run_transcode||"
)

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------

run_transcode() {
  omadora_exec omadora-transcode "$@"
}

# -----------------------------------------------------------------------------
# Completion
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

cli_main "$@"
