#!/usr/bin/env bash
set -euo pipefail

readonly OMADORA_LOG_TAG="omadora-service"

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# shellcheck source=lib/service.sh
source "$OMADORA_LIB_DIR/service.sh"

# TODO: Remove this comment
# Service: reboot/shutdown/lock/power-profile/timezone/status

# ----------------------------
# Usage
# ----------------------------
usage() {
  cat <<'EOF'
Usage:
  omactl service <command>

Commands:

EOF
}

# ----------------------------
# Completion
# ----------------------------
__complete() {
  local comp_words=("$@")
  local cmd="${comp_words[0]:-}"

  case "$cmd" in
  *)
    compgen -W "" -- "$cmd"
    ;;
  esac
}

# ----------------------------
# Dispatcher
# ----------------------------
cmd="${1:-}"

case "$cmd" in
"" | -h | --help | help)
  usage
  ;;

__complete)
  shift
  __complete "$@"
  ;;

*)
  usage >&2
  fatal "unknown command: $cmd"
  ;;
esac
