#!/usr/bin/env bash
set -euo pipefail

readonly OMADORA_LOG_TAG="omadora-service"

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# shellcheck source=lib/service.sh
source "$OMADORA_LIB_DIR/service.sh"

COMMANDS=(
  "reload"
)

SERVICES=(
  "alacritty"
  "ghostty"
  "hyprland"
  "kitty"
  "mako"
  "waybar"
)

# ----------------------------
# Usage
# ----------------------------
usage() {
  cat <<'EOF'
Usage:
  omactl service <command>

Commands:
EOF
  printf '  %s\n' "${COMMANDS[@]}"
  printf '\n'
}

# ----------------------------
# Completion
# ----------------------------
__complete() {
  local comp_words=("$@")
  local cmd="${comp_words[0]:-}"
  local cur=""

  if ((${#comp_words[@]})); then
    cur="${comp_words[${#comp_words[@]} - 1]}"
  fi

  case "$cmd" in
  #stop | restart | reload)
  #  systemctl --user list-units --type=service --state=running --no-legend --no-pager |
  #    awk '{print $1}'
  #  ;;
  status | start | stop | restart | reload)
    compgen -W "${SERVICES[*]}" -- "$cur"
    ;;

  *)
    compgen -W "${COMMANDS[*]}" -- "$cmd"
    ;;
  esac
}

# ----------------------------
# Dispatcher
# ----------------------------
service_dispatch() {
  local action="$1"
  local unit="$2"
  local fn="service_${action}_${unit}"

  if declare -F "$fn" >/dev/null; then
    "$fn"
  else
    #systemctl --user "$action" "${unit}.service"
    printf 'ERROR: function not found: %s\n' "${fn}" >&2
    exit 2
  fi
}

cmd="${1:-}"

case "$cmd" in
"" | -h | --help | help)
  usage
  ;;

status | start | stop | restart | reload)
  shift
  service_cmd="$cmd"
  service_name="${1:-}"

  if [[ -z "$service_name" ]]; then
    usage >&2
    printf 'ERROR: missing service name\n' >&2
    exit 2
  fi

  service_dispatch "$service_cmd" "$service_name"
  ;;

__complete)
  shift
  __complete "$@"
  ;;

*)
  usage >&2
  printf 'ERROR: unknown command: %s\n' "$cmd" >&2
  exit 2
  ;;
esac
