#!/usr/bin/env bash
set -euo pipefail

readonly OMADORA_LOG_TAG="omadora-doctor"

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# ----------------------------
# Usage
# ----------------------------
usage() {
  cat <<'EOF'
Usage:
  omactl doctor <command>

Commands:
  boot-errors
  recent-errors
  session-follow
  session-status

EOF
}

# ----------------------------
# Completion
# ----------------------------
__complete() {
  local comp_words=("$@")

  local cmd="${comp_words[0]:-}"
  #local cur=""

  #if ((${#comp_words[@]})); then
  #  cur="${comp_words[${#comp_words[@]} - 1]}"
  #fi

  case "$cmd" in
  boot-errors | recent-errors | session-follow | session-status)
    ;;

  *)
    compgen -W "boot-errors recent-errors session-follow session-status" -- "$cmd"
    ;;
  esac
}

# ----------------------------
# Dispatcher
# ----------------------------
cmd="${1:-}"

case "$cmd" in
"" | -h | --help | help)
  usage
  ;;

boot-errors)
  journalctl --user -p err -b
  ;;

recent-errors)
  journalctl --user -p err -n 50
  ;;

session-follow)
  journalctl --user -fu 'omadora-*'
  ;;

session-status)
  printf "\n%s\n" "Session Target Status:" "----------------------"
  systemctl --user --no-pager status omadora-session.target
  printf "\n%s\n" "Session Target Dependencies:" "-----------------------------"
  systemctl --user --no-pager list-dependencies omadora-session.target
  printf "\n%s\n" "Session Units:" "----------------"
  systemctl --user --no-pager --all list-units 'omadora-*'
  ;;

__complete)
  shift
  __complete "$@"
  ;;

*)
  usage >&2
  fatal "unknown command: $cmd"
  ;;
esac
