#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# shellcheck source=lib/update.sh
source "$OMADORA_LIB_DIR/update.sh"

COMMANDS=(
  "service-errors-boot"
  "service-errors-recent"
  "service-follow-omadora"
  "service-session-status"
  "update-state"
)

# ----------------------------
# Usage
# ----------------------------
usage() {
  cat <<'EOF'
Usage:
  omactl doctor <command>

Commands:
EOF
  printf '  %s\n' "${COMMANDS[@]}"
  printf '\n'
}

# ----------------------------
# Completion
# ----------------------------
__complete() {
  local comp_words=("$@")

  local cmd="${comp_words[0]:-}"
  #local cur=""

  #if ((${#comp_words[@]})); then
  #  cur="${comp_words[${#comp_words[@]} - 1]}"
  #fi

  case "$cmd" in
  boot-errors | recent-errors | session-follow | session-status)
    ;;

  *)
    compgen -W "${COMMANDS[*]}" -- "$cmd"
    ;;
  esac
}

# ----------------------------
# Dispatcher
# ----------------------------
cmd="${1:-}"

case "$cmd" in
"" | -h | --help | help)
  usage
  ;;

service-errors-boot)
  journalctl --user -p err -b
  ;;

service-errors-recent)
  journalctl --user -p err -n 50
  ;;

service-follow-omadora)
  journalctl --user -fu 'omadora-*'
  ;;

service-session-status)
  printf "Omadora Session Target Status:\n------------------------------\n"
  systemctl --user --legend=false --no-pager status omadora-session.target || true
  printf "\nOmadora Session Dependencies:\n-----------------------------\n"
  systemctl --user --legend=false --no-pager list-dependencies omadora-session.target || true
  printf "\nOmadora Session Units:\n----------------------\n"
  systemctl --user --legend=false --no-pager --all list-units 'omadora-*' || true
  printf "\nOmadora Session Timers:\n-----------------------\n"
  systemctl --user --legend=false --no-pager --all list-timers 'omadora-*' || true
  ;;

update-state)
  cat "$OMADORA_UPDATE_STATE_FILE" 2>/dev/null || true
  ;;

__complete)
  shift
  __complete "$@"
  ;;

*)
  usage >&2
  error "unknown command: $cmd"
  exit 2
  ;;
esac
