#!/usr/bin/env bash
set -euo pipefail

readonly OMADORA_LOG_TAG="omadora-update"

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# TODO: error logging etc.

echo -e "\e[32m\nUpdate system packages\e[0m"

#sudo dnf -q makecache --refresh
sudo dnf upgrade -y

# Fedora: use dnf needs-restarting to detect if a reboot is recommended/required.
# Non-zero exit status indicates a reboot is needed.
if ! sudo dnf needs-restarting >/dev/null 2>&1; then
  touch /run/reboot-required
fi
