#!/bin/bash

# Toggle Waybar Service

readonly flag="waybar-off"
readonly unit="waybar.service"

omadora-toggle "$flag"

if omadora-toggle-enabled "$flag"; then
  systemctl --quiet --user disable --now "$unit"
  notify-send -u low "󰍜    Waybar disabled"
else
  systemctl --quiet --user enable --now "$unit"
  notify-send -u low "󰍜    Waybar enabled"
fi

systemctl --user is-enabled "$unit"
