#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite all the user configs in ~/.config/hypr with the defaults.

omadora_run omadora-refresh-config hypr/autostart.conf
omadora_run omadora-refresh-config hypr/bindings.conf
omadora_run omadora-refresh-config hypr/input.conf
omadora_run omadora-refresh-config hypr/looknfeel.conf
omadora_run omadora-refresh-config hypr/hyprland.conf
omadora_run omadora-refresh-config hypr/monitors.conf
