#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite the user configs for the Waybar menu bar with the defaults and restart the service.

omadora_run omadora-refresh-config waybar/config.jsonc
omadora_run omadora-refresh-config waybar/style.css
omadora_run omadora-restart-waybar
