#!/usr/bin/env bash
set -euo pipefail

readonly OMADORA_LOG_TAG="omadora-update"

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# TODO: error logging etc.

require_cmd flatpak

echo -e "\e[32m\nUpdate Flatpaks\e[0m"

flatpak update -y
