#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Toggle screensaver availability

omadora_run omadora-toggle \
  --enabled-notification "󱄄   Screensaver disabled" \
  --disabled-notification "󱄄   Screensaver enabled" \
  screensaver-off
