#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Launch a TUI or focus an existing terminal window for it

APP_ID="org.omadora.$(basename "$1")"
LAUNCH_COMMAND="$(omadora_command omadora-launch-tui "$@")"

omadora_exec omadora-launch-or-focus "$APP_ID" "$LAUNCH_COMMAND"
