#!/bin/bash

# Toggle Waybar Service

readonly flag="waybar-off"
readonly unit="waybar.service"

omadora-toggle "$flag"

if omadora-toggle-enabled "$flag"; then
  systemctl --quiet --user stop "$unit"
  notify-send -u low "󰍜    Waybar disabled"
else
  systemctl --quiet --user start "$unit"
  notify-send -u low "󰍜    Waybar enabled"
fi
