#!/usr/bin/env bash
set -euo pipefail

# Install a wrapper for a given flatpak cli command.

if [[ -z $1 ]]; then
  echo "Usage: omadora-flatpak-cmd-install <package> [command-name]"
  exit 1
fi

package=$1
command=${2:-$1}

mkdir -p "$HOME/.local/bin"

cat >"$HOME/.local/bin/$command" <<EOF
#!/usr/bin/env bash
exec flatpak run --command="$command" "$package"
EOF

chmod +x "$HOME/.local/bin/$command"
