#!/bin/bash

# Launch or focus on a given TUI identified by the passed in as the command.
# Use by commands like omadora-launch-wifi to ensure there is only one wifi configuration screen open.

APP_ID="org.omadora.$(basename "$1")"
LAUNCH_COMMAND="omadora-launch-tui $@"

exec omadora-launch-or-focus "$APP_ID" "$LAUNCH_COMMAND"
