#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Toggles the window gaps globally between no gaps and the default.

omadora_run omadora-hyprland-toggle window-no-gaps
