#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite the user configs for Wofi with the defaults.

omadora_run omadora-refresh-config wofi/config
omadora_run omadora-refresh-config wofi/style.css
