#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# shellcheck source=lib/service.sh
source "$OMADORA_LIB_DIR/service.sh"

# Reload theme components. This is used after applying a new theme to ensure all components are using the new theme.
#
service_reload_waybar || true
service_reload_mako || true
service_reload_hyprland || true
service_reload_btop || true
service_reload_alacritty || true
service_reload_ghostty || true
service_reload_kitty || true
