#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite the user tmux config with the Omadora default and reload tmux.

omadora_run omadora-refresh-config tmux/tmux.conf
omadora_run omadora-restart-tmux
