#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Run all pending migrations to bring the system in line with the installed version.

# Where we store an empty file for each migration that has already been performed.
OMADORA_MIGRATIONS_STATE_DIR="$HOME/.local/state/omadora/migrations"
ensure_dir "$OMADORA_MIGRATIONS_STATE_DIR"

# Skipped migrations are tracked separately
ensure_dir "$OMADORA_MIGRATIONS_STATE_DIR/skipped"

# Run any pending migrations
for file in "${OMADORA_MIGRATIONS_DIR}"/*.sh; do
  filename="${file##*/}"

  if [[ ! -f "$OMADORA_MIGRATIONS_STATE_DIR/$filename" && ! -f "$OMADORA_MIGRATIONS_STATE_DIR/skipped/$filename" ]]; then
    info "Migrating => ${filename%.sh}"

    if bash "$file"; then
      touch "$OMADORA_MIGRATIONS_STATE_DIR/$filename"
    else
      # Migrations should not fail, so don't offer to skip. Instead, just exit and let the user fix the underlying issue.
      die "migration ${filename%.sh} failed"
    fi
  fi
done

info "Done."
