#!/bin/bash

# Toggle Weather Checks

readonly flag="weather-check-off"
readonly unit="omadora-weather-check.timer"

omadora-toggle "$flag"

if omadora-toggle-enabled "$flag"; then
  systemctl --quiet --user stop "$unit"
  notify-send -u low "    Weather disabled"
else
  systemctl --quiet --user start "$unit"
  notify-send -u low "    Weather enabled"
fi

pkill -RTMIN+11 waybar || true
