#!/usr/bin/env bash
set -euo pipefail

# Install a wrapper for a given flatpak cli cmd.

if [[ -z $1 ]]; then
  echo "Usage: omadora-flatpak-cmd-install <package> <command>"
  exit 1
fi

pkg=$1
cmd=$2

mkdir -p "$HOME/.local/bin"

cat >"$HOME/.local/bin/$cmd" <<EOF
#!/usr/bin/env bash
flatpak run --command="$cmd" "$pkg" "\$@"
EOF

chmod +x "$HOME/.local/bin/$cmd"
