#!/bin/bash

# Creates a new Omadora migration named after the unix timestamp of the last commit.
# Only intended for Omadora developers.

cd ~/.local/share/omadora || exit 1
migration_file="$HOME/.local/share/omadora/migrations/$(git log -1 --format=%cd --date=unix).sh"
touch "$migration_file"

if [[ "$1" != "--no-edit" ]]; then
  nvim "$migration_file"
fi

echo "$migration_file"
