#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

require_cmd git

git -C "$OMADORA_ROOT" pull --autostash ||
  die "failed to pull git updates"

git -C "$OMADORA_ROOT" --no-pager diff --check ||
  git -C "$OMADORA_ROOT" reset --merge
