#!/usr/bin/env bash
set -euo pipefail

readonly OMADORA_LOG_TAG="omadora-update"

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# TODO: Review

require_cmd cargo

cargo install-update --version >/dev/null 2>&1 ||
  fatal "cargo install-update missing"

echo -e "\e[32m\nUpdate Cargo bins\e[0m"

cargo install-update --all
