#!/bin/bash

# shellcheck source=lib/common/init.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common/init.sh"

# Overwrite the user config for hyprsunset with the default and restart the service.

omadora_run omadora-refresh-config hypr/hyprsunset.conf
omadora_run omadora-restart-hyprsunset
