#!/bin/bash

# Run the first-run scripts and welcome.

set -e

FIRST_RUN_MODE="$HOME/.local/state/omadora/first-run.mode"

if [[ -f $FIRST_RUN_MODE ]]; then
  rm -f "$FIRST_RUN_MODE"

  bash "$OMADORA_PATH/install/first-run/gdk-scale.sh"
  bash "$OMADORA_PATH/install/first-run/welcome.sh"
fi
