#!/bin/bash

# Set the system-wide monospace font that should be used by the terminal, etc.
# The font name must be one of the ones returned by omadora-font-list.

font_name="$1"

if [[ -n "$font_name" ]]; then
  if fc-list | grep -iq "$font_name"; then
    if [[ -f ~/.config/alacritty/alacritty.toml ]]; then
      sed -i "s/family = \"[^\"]*\"/family = \"$font_name\"/g" ~/.config/alacritty/alacritty.toml
    fi

    if [[ -f ~/.config/kitty/kitty.conf ]]; then
      sed -i "s/^font_family .*/font_family $font_name/g" ~/.config/kitty/kitty.conf
      pkill -USR1 kitty
    fi

    if [[ -f ~/.config/ghostty/config ]]; then
      sed -i "s/^\(font-family[^=]*=\) \".*\"$/\1 \"$font_name\"/" ~/.config/ghostty/config
      pkill -SIGUSR2 ghostty
    fi

    xmlstarlet ed -L \
      -u '//match[@target="pattern"][test/string="monospace"]/edit[@name="family"]/string' \
      -v "$font_name" \
      ~/.config/fontconfig/fonts.conf

    if pgrep -x ghostty; then
      notify-send "    You must restart Ghostty to see font change"
    fi

    gsettings set org.gnome.desktop.interface font-name "Adwaita Sans 11"
    gsettings set org.gnome.desktop.interface document-font-name "Adwaita Sans 12"
    gsettings set org.gnome.desktop.interface monospace-font-name "$font_name 10"

    omadora-hook font-set "$font_name"
  else
    echo "Font '$font_name' not found."
    exit 1
  fi
else
  echo "Usage: omadora-font-set <font-name>"
fi
