#!/bin/bash

# Designed to be run by systemd timer every 30 seconds and alerts if battery is low

BATTERY_THRESHOLD=10
NOTIFICATION_FLAG="/run/user/$UID/omadora_battery_notified"

battery_level=$(omadora-battery-remaining)
battery_state=$(upower -i $(upower -e | grep 'BAT') | grep -E "state" | awk '{print $2}')

send_notification() {
  notify-send -u critical "󱐋 Time to recharge!" "Battery is down to ${1}%" -i battery-caution -t 30000
}

if [[ -n "$battery_level" && "$battery_level" =~ ^[0-9]+$ ]]; then
  if [[ $battery_state == "discharging" && $battery_level -le $BATTERY_THRESHOLD ]]; then
    if [[ ! -f $NOTIFICATION_FLAG ]]; then
      send_notification "$battery_level"
      touch $NOTIFICATION_FLAG
    fi
  else
    rm -f $NOTIFICATION_FLAG
  fi
fi
