#!/bin/bash

# Launch a floating terminal with the logo presentation, then execute the command passed in, and finally end with the omadora-show-done presentation.
# Used by actions such as Update System.

cmd="$*"
exec setsid uwsm-app -- alacritty --class=org.omadora.terminal --title=Omadora -e bash -c "omadora-show-logo; $cmd; if [ \$? -ne 130 ]; then omadora-show-done; fi"
