-- local set = vim.api.nvim_set_hl
--
-- local c = {
--   bg = "#050505",
--   bg_alt = "#101010",
--   bg_dim = "#202020",
--
--   fg = "#bfbfbf",
--
--   accent = "#00d7d7",
--   cyan = "#5fffff",
--   blue = "#3f5fff",
--   green = "#00d700",
--   yellow = "#d7d700",
--   red = "#d70000",
--   magenta = "#d700d7",
--
--   gray = "#909090",
--   darkgray = "#505050",
--
--   black = "#000000",
--   white = "#ffffff",
-- }
--
-- vim.api.nvim_create_autocmd("ColorScheme", {
--   callback = function()
--     -- all set() calls here
--     -- Core UI
--     set(0, "Normal", {
--       fg = c.fg,
--       bg = c.bg,
--     })
--
--     set(0, "NormalNC", {
--       fg = "#9a9a9a",
--       bg = c.bg,
--     })
--
--     set(0, "EndOfBuffer", {
--       fg = c.bg,
--       bg = c.bg,
--     })
--
--     set(0, "NonText", {
--       fg = c.darkgray,
--       bg = c.bg,
--     })
--
--     set(0, "CursorLine", {
--       bg = c.bg_alt,
--     })
--
--     set(0, "Visual", {
--       fg = c.black,
--       bg = c.accent,
--     })
--
--     set(0, "Search", {
--       fg = c.black,
--       bg = c.yellow,
--     })
--
--     set(0, "IncSearch", {
--       fg = c.black,
--       bg = c.cyan,
--     })
--
--     set(0, "LineNr", {
--       fg = c.darkgray,
--       bg = c.bg,
--     })
--
--     set(0, "CursorLineNr", {
--       fg = c.cyan,
--       bold = true,
--     })
--
--     set(0, "WinSeparator", {
--       fg = "#303030",
--       bg = c.bg,
--     })
--
--     -- Syntax
--     set(0, "Comment", {
--       fg = c.gray,
--       italic = true,
--     })
--
--     set(0, "Constant", {
--       fg = c.magenta,
--     })
--
--     set(0, "String", {
--       fg = c.green,
--     })
--
--     set(0, "Identifier", {
--       fg = c.fg,
--     })
--
--     set(0, "Function", {
--       fg = c.cyan,
--     })
--
--     set(0, "Statement", {
--       fg = c.accent,
--       bold = true,
--     })
--
--     set(0, "Type", {
--       fg = c.blue,
--     })
--
--     set(0, "Keyword", {
--       fg = c.cyan,
--     })
--
--     set(0, "PreProc", {
--       fg = c.yellow,
--     })
--
--     set(0, "Error", {
--       fg = c.white,
--       bg = c.red,
--       bold = true,
--     })
--
--     set(0, "Todo", {
--       fg = c.black,
--       bg = c.yellow,
--       bold = true,
--     })
--
--     -- Floats / popup menus
--     set(0, "NormalFloat", {
--       fg = c.fg,
--       bg = c.bg,
--     })
--
--     set(0, "FloatBorder", {
--       fg = c.darkgray,
--       bg = c.bg,
--     })
--
--     set(0, "FloatTitle", {
--       fg = c.accent,
--       bg = c.bg,
--       bold = true,
--     })
--
--     set(0, "Pmenu", {
--       fg = c.fg,
--       bg = c.bg_alt,
--     })
--
--     set(0, "PmenuSel", {
--       fg = c.black,
--       bg = c.accent,
--     })
--
--     set(0, "PmenuSbar", {
--       bg = c.bg_dim,
--     })
--
--     set(0, "PmenuThumb", {
--       bg = c.gray,
--     })
--
--     -- Diagnostics
--     set(0, "DiagnosticError", {
--       fg = c.red,
--     })
--
--     set(0, "DiagnosticWarn", {
--       fg = c.yellow,
--     })
--
--     set(0, "DiagnosticInfo", {
--       fg = c.cyan,
--     })
--
--     set(0, "DiagnosticHint", {
--       fg = c.green,
--     })
--
--     -- Structural UI
--     set(0, "SignColumn", {
--       bg = c.bg,
--     })
--
--     set(0, "FoldColumn", {
--       fg = c.darkgray,
--       bg = c.bg,
--     })
--
--     set(0, "StatusLine", {
--       fg = c.fg,
--       bg = c.bg_alt,
--     })
--
--     set(0, "StatusLineNC", {
--       fg = c.gray,
--       bg = "#0b0b0b",
--     })
--
--     -- Git
--     set(0, "GitSignsAdd", {
--       fg = c.green,
--       bg = c.bg,
--     })
--
--     set(0, "GitSignsChange", {
--       fg = c.yellow,
--       bg = c.bg,
--     })
--
--     set(0, "GitSignsDelete", {
--       fg = c.red,
--       bg = c.bg,
--     })
--
--     set(0, "MatchParen", {
--       fg = c.black,
--       bg = c.cyan,
--       bold = true,
--     })
--   end,
-- })

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "ron",
    },
  },
}
