# Gum Style (generic) Variables
FOREGROUND="{{ foreground }}"
BACKGROUND="{{ background }}"
BORDER_FOREGROUND="{{ accent }}"
BORDER_BACKGROUND="{{ background }}"

# Gum Confirm Style Variables
GUM_CONFIRM_PROMPT_FOREGROUND="{{ accent }}"
GUM_CONFIRM_PROMPT_BACKGROUND="{{ background }}"
GUM_CONFIRM_SELECTED_FOREGROUND="{{ selection_foreground }}"
GUM_CONFIRM_SELECTED_BACKGROUND="{{ selection_background }}"
GUM_CONFIRM_UNSELECTED_FOREGROUND="{{ foreground }}"
GUM_CONFIRM_UNSELECTED_BACKGROUND="{{ background }}"

# Gum Input Style Variables
GUM_INPUT_PROMPT_FOREGROUND="{{ accent }}"
GUM_INPUT_PROMPT_BACKGROUND="{{ background }}"
GUM_INPUT_PLACEHOLDER_FOREGROUND="{{ color8 }}"
GUM_INPUT_PLACEHOLDER_BACKGROUND="{{ background }}"
GUM_INPUT_CURSOR_FOREGROUND="{{ cursor }}"
GUM_INPUT_CURSOR_BACKGROUND="{{ background }}"
GUM_INPUT_HEADER_FOREGROUND="{{ foreground }}"
GUM_INPUT_HEADER_BACKGROUND="{{ background }}"

# Gum Choose Style Variables
GUM_CHOOSE_CURSOR_FOREGROUND="{{ accent }}"
GUM_CHOOSE_CURSOR_BACKGROUND="{{ background }}"
GUM_CHOOSE_HEADER_FOREGROUND="{{ foreground }}"
GUM_CHOOSE_HEADER_BACKGROUND="{{ background }}"
GUM_CHOOSE_ITEM_FOREGROUND="{{ foreground }}"
GUM_CHOOSE_ITEM_BACKGROUND="{{ background }}"
GUM_CHOOSE_SELECTED_FOREGROUND="{{ selection_foreground }}"
GUM_CHOOSE_SELECTED_BACKGROUND="{{ selection_background }}"

# Gum Filter Style Variables
GUM_FILTER_PROMPT_FOREGROUND="{{ accent }}"
GUM_FILTER_PROMPT_BACKGROUND="{{ background }}"
GUM_FILTER_TEXT_FOREGROUND="{{ foreground }}"
GUM_FILTER_TEXT_BACKGROUND="{{ background }}"
GUM_FILTER_MATCH_FOREGROUND="{{ accent }}"
GUM_FILTER_CURSOR_TEXT_FOREGROUND="{{ cursor }}"
GUM_FILTER_CURSOR_TEXT_BACKGROUND="{{ background }}"
GUM_FILTER_SELECTED_FOREGROUND="{{ selection_foreground }}"
GUM_FILTER_SELECTED_BACKGROUND="{{ selection_background }}"
GUM_FILTER_INDICATOR_FOREGROUND="{{ accent }}"
GUM_FILTER_HEADER_FOREGROUND="{{ foreground }}"
GUM_FILTER_MATCH_BACKGROUND="{{ background }}"
GUM_FILTER_HEADER_BACKGROUND="{{ background }}"
GUM_FILTER_PLACEHOLDER_FOREGROUND="{{ color8 }}"
GUM_FILTER_PLACEHOLDER_BACKGROUND="{{ background }}"
GUM_FILTER_INDICATOR_BACKGROUND="{{ background }}"
GUM_FILTER_SELECTED_PREFIX_FOREGROUND="{{ selection_foreground }}"
GUM_FILTER_SELECTED_PREFIX_BACKGROUND="{{ selection_background }}"
GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="{{ color8 }}"
GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND="{{ background }}"

# Gum Table Style Variables
GUM_TABLE_HEADER_FOREGROUND="{{ foreground }}"
GUM_TABLE_HEADER_BACKGROUND="{{ background }}"
GUM_TABLE_CELL_FOREGROUND="{{ foreground }}"
GUM_TABLE_CELL_BACKGROUND="{{ background }}"
GUM_TABLE_BORDER_FOREGROUND="{{ color8 }}"
GUM_TABLE_BORDER_BACKGROUND="{{ background }}"
GUM_TABLE_SELECTED_FOREGROUND="{{ selection_foreground }}"
GUM_TABLE_SELECTED_BACKGROUND="{{ selection_background }}"

# Gum Spin Style Variables
GUM_SPIN_SPINNER_FOREGROUND="{{ accent }}"
GUM_SPIN_SPINNER_BACKGROUND="{{ background }}"
GUM_SPIN_TITLE_FOREGROUND="{{ foreground }}"
GUM_SPIN_TITLE_BACKGROUND="{{ background }}"

# Gum File Style Variables
GUM_FILE_CURSOR_FOREGROUND="{{ cursor }}"
GUM_FILE_CURSOR_BACKGROUND="{{ background }}"
GUM_FILE_SYMLINK_FOREGROUND="{{ foreground }}"
GUM_FILE_SYMLINK_BACKGROUND="{{ background }}"
GUM_FILE_DIRECTORY_FOREGROUND="{{ foreground }}"
GUM_FILE_DIRECTORY_BACKGROUND="{{ background }}"
GUM_FILE_FILE_FOREGROUND="{{ foreground }}"
GUM_FILE_FILE_BACKGROUND="{{ background }}"
GUM_FILE_PERMISSIONS_FOREGROUND="{{ color8 }}"
GUM_FILE_PERMISSIONS_BACKGROUND="{{ background }}"
GUM_FILE_SELECTED_FOREGROUND="{{ selection_foreground }}"
GUM_FILE_SELECTED_BACKGROUND="{{ selection_background }}"
GUM_FILE_FILE_SIZE_FOREGROUND="{{ color8 }}"
GUM_FILE_FILE_SIZE_BACKGROUND="{{ background }}"
GUM_FILE_HEADER_FOREGROUND="{{ foreground }}"
GUM_FILE_HEADER_BACKGROUND="{{ background }}"

# Gum Pager Style Variables
GUM_PAGER_FOREGROUND="{{ foreground }}"
GUM_PAGER_BACKGROUND="{{ background }}"
GUM_PAGER_LINE_NUMBER_FOREGROUND="{{ color8 }}"
GUM_PAGER_LINE_NUMBER_BACKGROUND="{{ background }}"
GUM_PAGER_MATCH_FOREGROUND="{{ accent }}"
GUM_PAGER_MATCH_BACKGROUND="{{ background }}"
GUM_PAGER_MATCH_HIGH_FOREGROUND="{{ accent }}"
GUM_PAGER_MATCH_HIGH_BACKGROUND="{{ background }}"
GUM_PAGER_HELP_FOREGROUND="{{ color8 }}"
GUM_PAGER_HELP_BACKGROUND="{{ background }}"

# Gum Write Style Variables
GUM_WRITE_BASE_FOREGROUND="{{ foreground }}"
GUM_WRITE_BASE_BACKGROUND="{{ background }}"
GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND="{{ color8 }}"
GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND="{{ background }}"
GUM_WRITE_CURSOR_LINE_FOREGROUND="{{ foreground }}"
GUM_WRITE_CURSOR_LINE_BACKGROUND="{{ selection_background }}"
GUM_WRITE_CURSOR_FOREGROUND="{{ cursor }}"
GUM_WRITE_CURSOR_BACKGROUND="{{ background }}"
GUM_WRITE_END_OF_BUFFER_FOREGROUND="{{ color8 }}"
GUM_WRITE_END_OF_BUFFER_BACKGROUND="{{ background }}"
GUM_WRITE_LINE_NUMBER_FOREGROUND="{{ color8 }}"
GUM_WRITE_LINE_NUMBER_BACKGROUND="{{ background }}"
GUM_WRITE_HEADER_FOREGROUND="{{ foreground }}"
GUM_WRITE_HEADER_BACKGROUND="{{ background }}"
GUM_WRITE_PLACEHOLDER_FOREGROUND="{{ color8 }}"
GUM_WRITE_PLACEHOLDER_BACKGROUND="{{ background }}"
GUM_WRITE_PROMPT_FOREGROUND="{{ foreground }}"
GUM_WRITE_PROMPT_BACKGROUND="{{ background }}"

# Gum Log Style Variables
GUM_LOG_LEVEL_FOREGROUND="{{ accent }}"
GUM_LOG_LEVEL_BACKGROUND="{{ background }}"
GUM_LOG_TIME_FOREGROUND="{{ color8 }}"
GUM_LOG_TIME_BACKGROUND="{{ background }}"
GUM_LOG_PREFIX_FOREGROUND="{{ foreground }}"
GUM_LOG_PREFIX_BACKGROUND="{{ background }}"
GUM_LOG_MESSAGE_FOREGROUND="{{ foreground }}"
GUM_LOG_MESSAGE_BACKGROUND="{{ background }}"
GUM_LOG_KEY_FOREGROUND="{{ foreground }}"
GUM_LOG_KEY_BACKGROUND="{{ background }}"
GUM_LOG_VALUE_FOREGROUND="{{ foreground }}"
GUM_LOG_VALUE_BACKGROUND="{{ background }}"
GUM_LOG_SEPARATOR_FOREGROUND="{{ color8 }}"
GUM_LOG_SEPARATOR_BACKGROUND="{{ background }}"
