# Menus
bindd = SUPER, SPACE, Launch apps, exec, omadora-menu apps
bindd = SUPER CTRL, C, Capture menu, exec, omadora-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, omadora-menu toggle
bindd = SUPER CTRL, H, Hardware menu, exec, omadora-menu hardware
bindd = SUPER ALT, SPACE, Omadora menu, exec, omadora-menu
bindd = SUPER SHIFT, code:201, Omadora menu, exec, omadora-menu
bindd = SUPER, ESCAPE, System menu, exec, omadora-menu system
bindld = , XF86PowerOff, Power menu, exec, omadora-menu system
bindd = SUPER, K, Show key bindings, exec, omadora-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, omactl workspace toggle-waybar
bindd = SUPER CTRL, SPACE, Next theme background, exec, omactl theme bg-next
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, omadora-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, omadora-hyprland-window-transparency-toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, omadora-hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, omadora-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, omadora-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, omadora-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, omadora-toggle-nightlight
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, omadora-hyprland-monitor-internal toggle
bindd = SUPER CTRL ALT, Delete, Toggle laptop display mirroring, exec, omadora-hyprland-monitor-internal-mirror toggle
bindl = , switch:on:Lid Switch, exec, omadora-hw-external-monitors && omadora-hyprland-monitor-internal off
bindl = , switch:off:Lid Switch, exec, omadora-hyprland-monitor-internal on

# Captures
bindd = , PRINT, Screenshot with editing, exec, omadora-capture-screenshot
bindd = ALT, PRINT, Screenrecording, exec, omadora-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER CTRL, PRINT, Extract text (OCR) from screenshot, exec, omadora-capture-text-extraction

# Reminders
bindd = SUPER CTRL, R, Set reminder, exec, omadora-menu reminder-set
bindd = SUPER CTRL ALT, R, Show reminders, exec, omadora-reminder show
bindd = SUPER SHIFT CTRL, R, Clear reminders, exec, omadora-reminder clear

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(omadora-battery-status)"
bindd = SUPER CTRL ALT, W, Show weather, exec, notify-send -u low "$(omadora-weather-status)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, omadora-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, omadora-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, omadora-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, omadora-launch-system-monitor

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, omactl system lock
