# Menus
bindd = SUPER, SPACE, Launch apps, exec, omadora-exec omadora-menu apps
bindd = SUPER CTRL, C, Capture menu, exec, omadora-exec omadora-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, omadora-exec omadora-menu toggle
bindd = SUPER CTRL, H, Hardware menu, exec, omadora-exec omadora-menu hardware
bindd = SUPER ALT, SPACE, Omadora menu, exec, omadora-exec omadora-menu
bindd = SUPER SHIFT, code:201, Omadora menu, exec, omadora-exec omadora-menu
bindd = SUPER, ESCAPE, System menu, exec, omadora-exec omadora-menu system
bindld = , XF86PowerOff, Power menu, exec, omadora-exec omadora-menu system
bindd = SUPER, K, Show key bindings, exec, omadora-exec omadora-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, omactl ui toggle waybar
bindd = SUPER CTRL, SPACE, Next theme background, exec, omactl theme background next
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, omadora-exec omadora-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, omactl ui toggle window-transparency
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, omactl ui toggle gaps
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, omactl ui toggle single-window-aspect

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, omactl toggle notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER SHIFT, W, Toggle weather, exec, omactl toggle weather
bindd = SUPER CTRL, I, Toggle locking on idle, exec, omactl toggle idle-lock
bindd = SUPER CTRL, N, Toggle nightlight, exec, omactl toggle nightlight
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, omactl display internal toggle
bindd = SUPER CTRL ALT, Delete, Toggle laptop display mirroring, exec, omactl display internal-mirror toggle
bindl = , switch:on:Lid Switch, exec, omadora-exec omadora-hw-external-monitors && omactl display internal off
bindl = , switch:off:Lid Switch, exec, omactl display internal on

# Captures
bindd = , PRINT, Screenshot with editing, exec, omactl capture screenshot
bindd = ALT, PRINT, Screenrecording, exec, omadora-exec omadora-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER CTRL, PRINT, Extract text (OCR) from screenshot, exec, omactl capture text-extraction

# Reminders
bindd = SUPER CTRL, R, Set reminder, exec, omadora-exec omadora-menu reminder-set
bindd = SUPER CTRL ALT, R, Show reminders, exec, omadora-exec omadora-reminder show
bindd = SUPER SHIFT CTRL, R, Clear reminders, exec, omadora-exec omadora-reminder clear

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(omactl info battery)"
bindd = SUPER CTRL ALT, W, Show weather, exec, notify-send -u low "$(omactl info weather)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, omadora-exec omadora-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, omadora-exec omadora-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, omadora-exec omadora-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, omadora-exec omadora-launch-system-monitor

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, omactl session lock
